Repository Sameer25-py/Dungeon-Survivor, pull requests merged in 2023-02, with the labels that each got.

#1 implment navmesh functionality
  Assets/Art/Materials/Navmesh.meta
  Assets/Art/Materials/Navmesh/Navmesh.mat
  Assets/Art/Materials/Navmesh/Navmesh.mat.meta
  Assets/Art/Materials/Navmesh/NavmeshPlayer.mat
  Assets/Art/Materials/Navmesh/NavmeshPlayer.mat.meta
  Assets/Art/Materials/Navmesh/Points.mat
  Assets/Art/Materials/Navmesh/Points.mat.meta
  Assets/Scenes/Navmesh.meta
  Assets/Scenes/Navmesh.unity
  Assets/Scenes/Navmesh.unity.meta
  Assets/Scenes/Navmesh/NavMesh.asset
  Assets/Scenes/Navmesh/NavMesh.asset.meta
  Assets/Scripts/Core.meta
  Assets/Scripts/Core/Events.meta
  Assets/Scripts/Core/Events/GameplayEvents.cs
  Assets/Scripts/Core/Events/GameplayEvents.cs.meta
  Assets/Scripts/Core/Input.meta
  Assets/Scripts/Core/Input/InputController.cs
  Assets/Scripts/Core/Input/InputController.cs.meta
  Assets/Scripts/Core/Player.meta
  Assets/Scripts/Core/Player/MovementController.cs
  Assets/Scripts/Core/Player/MovementController.cs.meta
  Assets/Scripts/MainAssembly.asmdef
  Assets/Scripts/MainAssembly.asmdef.meta
  ProjectSettings/BurstAotSettings_Android.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/QualitySettings.asset
  UserSettings/EditorUserSettings.asset
Labels: enhancement

#3 Sameer/cinemachine camera follow
  .gitignore
  Assets/Scenes/Navmesh.unity
  Packages/manifest.json
  Packages/packages-lock.json
  UserSettings/EditorUserSettings.asset
Labels: enhancement

#4 Gates and Switches Working
  .idea/.idea.Dungeon-Survivor/.idea/workspace.xml
  Assets/Scenes/Rafay/RafayProto.unity
  Assets/Scripts/Core/Events/GameplayEvents.cs
  Assets/Scripts/Core/ID.meta
  Assets/Scripts/Core/ID/IDManager.cs
  Assets/Scripts/Core/ID/IDManager.cs.meta
  Assets/Scripts/Core/Puzzles.meta
  Assets/Scripts/Core/Puzzles/Gate.cs
  Assets/Scripts/Core/Puzzles/Gate.cs.meta
  Assets/Scripts/Core/Puzzles/Link.cs
  Assets/Scripts/Core/Puzzles/Link.cs.meta
  Assets/Scripts/Core/Puzzles/PermanentSwitch.cs
  Assets/Scripts/Core/Puzzles/PermanentSwitch.cs.meta
  Assets/Scripts/Core/Puzzles/TemporarySwitch.cs
  Assets/Scripts/Core/Puzzles/TemporarySwitch.cs.meta
  UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#9 implment door open and close animation
  Assets/Art/3D/DoorAndSwitches/Switches/SwitchTex/SwitchBase_Brick1_Normal.png.meta
  Assets/Prefabs/Environment.meta
  Assets/Prefabs/Environment/Door.meta
  Assets/Prefabs/Environment/Door/DoorParent.prefab
  Assets/Prefabs/Environment/Door/DoorParent.prefab.meta
  Assets/Scenes/Sameer/Door.unity
  Assets/Scenes/Sameer/Door.unity.meta
  Assets/Scripts/Controllers/Animations.meta
  Assets/Scripts/Controllers/Animations/Door.meta
  Assets/Scripts/Controllers/Animations/Door/DoorAnimator.cs
  Assets/Scripts/Controllers/Animations/Door/DoorAnimator.cs.meta
  UserSettings/EditorUserSettings.asset
Labels: enhancement

#10 Sameer/animate switch
  Assets/Art/Materials/Switch.meta
  Assets/Art/Materials/Switch/Switch.mat
  Assets/Art/Materials/Switch/Switch.mat.meta
  Assets/Prefabs/Environment/Doors.meta
  Assets/Prefabs/Environment/Doors/DoorParent.prefab
  Assets/Prefabs/Environment/Doors/DoorParent.prefab.meta
  Assets/Prefabs/Environment/Switches.meta
  Assets/Prefabs/Environment/Switches/CircleSwitch.prefab
  Assets/Prefabs/Environment/Switches/CircleSwitch.prefab.meta
  Assets/Prefabs/Environment/Switches/HexagonSwich.prefab
  Assets/Prefabs/Environment/Switches/HexagonSwich.prefab.meta
  Assets/Prefabs/Environment/Switches/SquareSwitch.prefab
  Assets/Prefabs/Environment/Switches/SquareSwitch.prefab.meta
  Assets/Prefabs/Environment/Switches/TriangleSwitch.prefab
  Assets/Prefabs/Environment/Switches/TriangleSwitch.prefab.meta
  Assets/Scenes/Sameer/Switch.unity
  Assets/Scenes/Sameer/Switch.unity.meta
  Assets/Scripts/Controllers/Animations/Switch.meta
  Assets/Scripts/Controllers/Animations/Switch/SwitchAnimator.cs
  Assets/Scripts/Controllers/Animations/Switch/SwitchAnimator.cs.meta
  UserSettings/EditorUserSettings.asset
Labels: enhancement

#11 wire up gates and switches w/ animators
  Assets/Prefabs/Environment/Switches/CircleSwitch.prefab
  Assets/Scenes/Sameer/DoorSwitch.meta
  Assets/Scenes/Sameer/DoorSwitch.unity
  Assets/Scenes/Sameer/DoorSwitch.unity.meta
  Assets/Scenes/Sameer/DoorSwitch/NavMesh.asset
  Assets/Scenes/Sameer/DoorSwitch/NavMesh.asset.meta
  Assets/Scripts/Controllers/Animations/Door/DoorAnimator.cs
  Assets/Scripts/Core/Puzzles/Gate.cs
  Assets/Scripts/Core/Puzzles/PermanentSwitch.cs
  Assets/Scripts/Core/Puzzles/TemporarySwitch.cs
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#13 move Editor scripts to Editor folder
  Assets/Editor.meta
  Assets/Editor/LevelEditorFunctionality.meta
  Assets/Editor/LevelEditorFunctionality/LevelEditor.cs
  Assets/Editor/LevelEditorFunctionality/LevelEditor.cs.meta
  Assets/Editor/LevelEditorFunctionality/LevelEditor.uss
  Assets/Editor/LevelEditorFunctionality/LevelEditor.uss.meta
  Assets/Editor/LevelEditorFunctionality/LevelEditor.uxml
  Assets/Editor/LevelEditorFunctionality/LevelEditor.uxml.meta
  Assets/Scripts/Editor.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: bug

#14 implment 4 direction movement
  Assets/Scenes/Rafay/GridProto.unity
  Assets/Scripts/Core/GridFunctionality/Grid.cs
  Assets/Scripts/Core/GridFunctionality/GridManager.cs
  Assets/Scripts/Core/Input/GridInputController.cs
  Assets/Scripts/Core/Player/Movement/GridMovement.cs
Labels: enhancement

#16 implment object push mechanic
  Assets/Scenes/Rafay/GridProto.unity
  Assets/Scenes/Rafay/GridProto.unity.meta
  Assets/Scripts/Core/Events/GameplayEvents.cs
  Assets/Scripts/Core/GridFunctionality/GridManager.cs
  Assets/Scripts/Core/Player/Controllers.meta
  Assets/Scripts/Core/Player/Controllers/GridPlayerController.cs
  Assets/Scripts/Core/Player/Controllers/GridPlayerController.cs.meta
  Assets/Scripts/Core/Player/Movement/GridMovement.cs
  Assets/Scripts/Core/Player/Movement/GridMovement.cs.meta
  Assets/Scripts/Core/Pushables.meta
  Assets/Scripts/Core/Pushables/PushableBase.cs
  Assets/Scripts/Core/Pushables/PushableBase.cs.meta
  Assets/Scripts/Core/Pushables/PushableBoulder.cs
  Assets/Scripts/Core/Pushables/PushableBoulder.cs.meta
  ProjectSettings/TagManager.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: enhancement, modification

#17 add logic to format timer string
  Assets/Scripts/Controllers/Countdown/TimerController.cs
Labels: enhancement

#18 add logic to track player moves
  Assets/Scripts/Analytics.meta
  Assets/Scripts/Analytics/Player.meta
  Assets/Scripts/Analytics/Player/PlayerDataHandler.cs
  Assets/Scripts/Analytics/Player/PlayerDataHandler.cs.meta
  Assets/Scripts/Core/Player/Controllers/GridPlayerController.cs
Labels: enhancement

#20 Rafay/integration
  Assets/Prefabs/Environment/Doors/DoorParent.prefab
  Assets/Prefabs/Environment/Switches/CircleSwitch.prefab
  Assets/Scenes/Rafay/Level1.unity
Labels: modification

#21 implment cinemachine camera follow
  Assets/Prefabs/CameraRigs/CinemachinePlayerFollow.prefab
  Assets/Prefabs/CameraRigs/CinemachinePlayerFollow.prefab.meta
  Assets/Scenes/Sameer/Level1_Cinemachine.unity
  UserSettings/Layouts/CurrentMaximizeLayout.dwlt
Labels: enhancement
